Upgrade displayAgent from v1.4 to v1.5
nugu-developers/nugu-ios pull request #468
Opened 2020-08-24 00:18 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-08-24 00:23 UTC, jin-marino commented on SampleApp/Sources/UI/MainViewController.swift
> +                NuguCentralManager.shared.client.textAgent.requestTextInput(text: textInput.text)
textInput 으로 이벤트 전달되었을때, NuguCentralManager.shared.client.textAgent.requestTextInput(text: textInput.text) 로 처리하면 되는것인지 확인 부탁드립니다~

2020-08-24 01:57 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
> +                NuguCentralManager.shared.client.textAgent.requestTextInput(text: textInput.text)
NuguCentralManager.shared.requestText 사용해야하고, playServiceId 도 전달해야합니다.
@yHoonyK 님, TextInterface 1.3 개발하면서 playServiceId 파라미터가 있는 requestTextInput 함수도 추가 부탁드려요.
이 경우 DM 과 무관하게 동작해야 할 것 같습니다.

2020-08-25 05:33 UTC, childc approved these changes

2020-08-25 09:03 UTC, yHoonyK approved these changes

2020-08-26 04:17 UTC, Minddol requested changes
나중에 TextAgent

2020-08-26 04:17 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
> +                NuguCentralManager.shared.client.textAgent.requestTextInput(text: textInput.text)
playServiceId 로 변경하는건 나중에 @yHoonyK 님이 작업 해주시면 변경하고,
우선 NuguCentralManager.shared.requestText 로만 바꿔주실 수 있을까요?

2020-08-26 05:28 UTC, jin-marino commented on SampleApp/Sources/UI/MainViewController.swift
> +                NuguCentralManager.shared.client.textAgent.requestTextInput(text: textInput.text)
반영하였습니다.

2020-08-26 05:29 UTC, Minddol requested changes

2020-08-26 05:29 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
> +                guard let textInput = textInput else { return }
DM 과 무관하게 동작하기 위해서 `includeDialogAttribute: false` 로 적용 부탁드려요...

2020-08-26 05:39 UTC, jin-marino commented on SampleApp/Sources/UI/MainViewController.swift
> +                guard let textInput = textInput else { return }
반영하였습니다~

2020-08-26 05:43 UTC, Minddol approved these changes

2020-08-26 05:56 UTC, merged