Change voice chrome dismiss logic
nugu-developers/nugu-ios pull request #493
Opened 2020-09-03 03:21 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-09-03 04:14 UTC, Minddol requested changes

2020-09-03 04:14 UTC, Minddol commented on SampleApp/Sources/Manager/NuguCentralManager.swift
@jin-marino 님, isMultiturnInProgress 를 저장하는 대신 DialogStateAggregator 에서 isMultiturn 을 public 으로 변경할께요

2020-09-03 10:29 UTC, childc approved these changes

2020-09-04 03:45 UTC, Minddol commented on SampleApp/Sources/Manager/NuguCentralManager.swift
@jin-marino 님, `DialogStateAggregator` 수정했습니다.

2020-09-08 01:36 UTC, jin-marino commented on SampleApp/Sources/Manager/NuguCentralManager.swift
반영하였습니다~

2020-09-08 01:42 UTC, Minddol approved these changes

2020-09-08 07:36 UTC, yHoonyK approved these changes

2020-09-09 01:26 UTC, merged