Modify access control of `DialogStateAggregator.sessionActivated` and…
nugu-developers/nugu-ios pull request #494
Opened 2020-09-03 04:22 UTC by Minddol

… `DialogStateAggregator.isMultiturn` from private to public.

## Check before PR

- [x] PR Title
- [x] Link issue or no issue to link
- [x] README.md
- [x] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [x] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-09-03 04:30 UTC, jin-marino approved these changes

2020-09-03 04:59 UTC, yHoonyK approved these changes

2020-09-03 10:26 UTC, childc requested changes

2020-09-03 10:26 UTC, childc commented on NuguClientKit/Sources/Business/DialogStateAggregator.swift
> +        !sessionManager.activeSessions.isEmpty
우리의 컨벤션대로..... 다음과 같이 변경 부탁드립니다

`sessionManager.activeSessions.isEmpty == false`

2020-09-03 10:26 UTC, childc commented on SampleApp/Sources/UI/MainViewController.swift
> +        log.debug(template.templateId)
코드를 보지 않아도 로그의미를 알 수 있게 다음과 같이 변경해주실 수 있나요?
`log.debug("templateId: \(template.templateId)")`

2020-09-04 01:00 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
> +        log.debug(template.templateId)
수정했습니다.

2020-09-04 01:00 UTC, Minddol commented on NuguClientKit/Sources/Business/DialogStateAggregator.swift
> +        !sessionManager.activeSessions.isEmpty
수정했습니다.

2020-09-04 03:40 UTC, childc approved these changes

2020-09-04 03:41 UTC, childc approved these changes

2020-09-04 03:45 UTC, merged