Apply detail error description
nugu-developers/nugu-ios pull request #506
Opened 2020-09-10 07:14 UTC by jin-marino

…u-sdk/authentication)

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-09-10 07:15 UTC, jin-marino commented
https://developers-doc.nugu.co.kr/nugu-sdk/authentication 에 맞추어 error description 추가하였습니다.

2020-09-10 07:37 UTC, yHoonyK approved these changes

2020-09-10 07:37 UTC, yHoonyK requested changes

2020-09-10 07:37 UTC, yHoonyK commented on SampleApp/Sources/Const/SampleAppError.swift
> +                    return "유효하지 않은 클라이언 정보입니다."
클라이언트 < 오타 있는것 같네요ㅎ

2020-09-10 07:43 UTC, jin-marino commented on SampleApp/Sources/Const/SampleAppError.swift
> +                    return "유효하지 않은 클라이언 정보입니다."
아 감사합니다, 수정했습니다.

2020-09-10 07:49 UTC, Minddol approved these changes

2020-09-10 09:16 UTC, yHoonyK approved these changes

2020-09-14 00:53 UTC, Minddol approved these changes

2020-09-14 02:32 UTC, merged