Add `TTSPlayer` and `AudioPlayer` to fix timing issues.
nugu-developers/nugu-ios pull request #560
Opened 2020-10-21 10:06 UTC by Minddol

## Check before PR

- [x] PR Title
- [x] Link issue or no issue to link
- [x] README.md
- [x] Code-level documentation

## Version

- [ ] Update major
- [x] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-10-22 05:57 UTC, Minddol commented
연관이슈 https://tde.sktelecom.com/pms/browse/AIAGENTQA-709

2020-10-26 03:03 UTC, Minddol commented
travis... waitUntil 에서 자꾸 timeout 나네요 ㅠ_ㅠ

2020-10-26 05:44 UTC, yHoonyK requested changes

2020-10-26 05:44 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
> -    public func mediaPlayerDidChange(state: MediaPlayerState) {
didChangeState state -> didChange state 가 더 자연스럽지 않을까요?

2020-10-26 05:44 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
> +    public func mediaPlayer(_ mediaPlayer: MediaPlayable, didChangeState state: MediaPlayerState) {
didChangeState state -> didChange state

2020-10-26 06:03 UTC, yHoonyK approved these changes

2020-10-26 06:03 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
> +    private var latesetPlayer: TTSPlayer? {
latesetPlayer -> latestPlayer

2020-10-26 06:04 UTC, yHoonyK requested changes
소소한 리뷰는 코멘트로 남겨뒀습니다.

2020-10-26 06:34 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
> -    public func mediaPlayerDidChange(state: MediaPlayerState) {
그렇네요~ 수정하겠습니다.

2020-10-26 06:34 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
> +            guard let player = self.latesetPlayer else { return }
수정했습니다~

2020-10-26 06:35 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
> +    func handleAttachment(attachment: Downstream.Attachment) -> Bool {
handleAttachment(_ attachment: ~) 이거로 수정하겠습니다.

2020-10-26 06:35 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
> +    private var latesetPlayer: TTSPlayer? {
수정했습니다~

2020-10-26 06:53 UTC, jin-marino approved these changes

2020-10-26 07:03 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
> -    public func mediaPlayerDidChange(state: MediaPlayerState) {
수정했습니다.

2020-10-26 07:04 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
> +    public func mediaPlayer(_ mediaPlayer: MediaPlayable, didChangeState state: MediaPlayerState) {
수정했습니다.

2020-10-26 07:04 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
> +    func handleAttachment(attachment: Downstream.Attachment) -> Bool {
수정했습니다.

2020-10-26 07:20 UTC, nugu-dev-sdk approved these changes

2020-10-26 07:24 UTC, childc approved these changes

2020-10-27 03:02 UTC, yHoonyK approved these changes

2020-10-27 03:05 UTC, merged