Make observer possible to be removed properly.
nugu-developers/nugu-ios pull request #650
Opened 2020-11-26 16:34 UTC by childc

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2020-11-26 16:38 UTC, childc commented on NuguCore/Sources/MediaPlayer/MediaAVPlayerItem.swift
> +        }
Block Base KVO swift 5.3으로 iOS 12~14테스트해보았습니다.

2020-11-26 16:40 UTC, childc commented on NuguLoginKit/Sources/Business/NuguOAuthClient.swift
> -        observer = nil
observer를 nil처리해도 등록한 closure가 해제되지 않고 계속해서 호출되는 것을 확인하였습니다

nil처리만으로도 observing이 종료되는 것은 Block Based KVO에서 적용됩니다.

2020-11-26 16:41 UTC, childc commented on SampleApp/Sources/Manager/NuguAudioSessionManager.swift
> +    private var audioEngineConfigurationObserver: Any?
정확한 type은 NSObjectProtocol이겠으나, NextStep관련 keyword를 될 수 있으면 사용하지 않는 것으로 하였습니다.

2020-11-26 16:43 UTC, childc commented on SampleApp/Sources/UI/MainViewController.swift
> -        NotificationCenter.default.removeObserver(self)
NotificationCenter에 observer를 단 경우, 이런식으로는 해제 되지 않는 경우가 많습니다.
(특히 multi-thread에서)

2020-11-27 03:01 UTC, Minddol requested changes

2020-11-27 03:01 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
> -        performSegue(withIdentifier: "showSettings", sender: nil)
테스트 코드 잘 못 들어간건가요?

2020-11-27 03:01 UTC, Minddol commented on SampleApp/Sources/UI/MainViewController.swift
>      @IBAction func startRecognizeButtonDidClick(_ button: UIButton) {
테스트 코드 잘 못 들어간건가요?

2020-11-27 03:04 UTC, Minddol commented
제 commit 이랑 충돌이 있어서 제가 resolve 했습니다 ㅋ

2020-11-27 05:45 UTC, childc commented on SampleApp/Sources/UI/MainViewController.swift
>      @IBAction func startRecognizeButtonDidClick(_ button: UIButton) {
큰일날 뻔 했네요 감사합니다

2020-11-30 00:24 UTC, Minddol commented
develop/0.28.0 으로 변경 부탁드려요, 
제가 conflict merge 한 commit 은 제거해야 될수도 있겠네요..

2020-12-02 07:12 UTC, childc commented
해당 PR close하고
0.28.0으로 머지하겠습니다.

2020-12-02 07:12 UTC, closed without merging