Use NotificationCenter rather than Delegate set.
nugu-developers/nugu-ios pull request #702
Opened 2021-01-09 09:36 UTC by childc

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-01-11 02:19 UTC, Minddol requested changes

2021-01-11 02:39 UTC, Minddol commented
https://nsscreencast.com/episodes/410-typed-notifications
찾아보면 구현 방법은 다양한 것 같은데요, 
사용하는 쪽에서 casting 안해도 되도록 지원해주는게 좋지 않을까요?

2021-01-12 05:17 UTC, childc reviewed
> https://nsscreencast.com/episodes/410-typed-notifications
> 찾아보면 구현 방법은 다양한 것 같은데요,
> 사용하는 쪽에서 casting 안해도 되도록 지원해주는게 좋지 않을까요?

그렇게되면 기본 제공되는 NotificationCenter가 아닌, 익숙하지 않은 별도의 API를 강제하게 됩니다.
또한 NuguUtils등을 import해야 합니다.

장단이 있으므로 이것은 추후 재논의하는 것이 좋을 것 같습니다.

2021-01-12 05:43 UTC, childc commented on NuguCore/Sources/Context/ContextInfoProvidable.swift
> +public typealias ProvideContextInfo = (_ completion: @escaping (ContextInfo?) -> Void) -> Void
> ContextInfoProvider로 변경

Protocol oriented기조는 그대로 유지하겠습니다.
우리가 처음 프로젝트를 시작할 때 결론지었던 것 처럼, 
모든 agent를 구현해줄 수 없고 언젠가는 3rd party에서 추가 구현할텐데, 
그때 다른 agent의 구현을 참고하지 않더라도 필수 또는 추천 구현사항은 알 수 있도록 해주는 것이 좋을 것 같아요

2021-01-12 05:44 UTC, childc commented on NuguCore/Sources/Context/ContextInfoProvidable.swift
> +     ///
Protocol oriented기조는 그대로 유지하겠습니다.
우리가 처음 프로젝트를 시작할 때 결론지었던 것 처럼,
모든 agent를 구현해줄 수 없고 언젠가는 3rd party에서 추가 구현할텐데,
그때 다른 agent의 구현을 참고하지 않더라도 필수 또는 추천 구현사항은 알 수 있도록 해주는 것이 좋을 것 같아요

2021-01-12 07:16 UTC, Minddol approved these changes

2021-01-13 07:24 UTC, yHoonyK approved these changes

2021-01-13 07:40 UTC, merged