Add `MessageAgent` 1.4 (upgrade capability-agent)
nugu-developers/nugu-ios pull request #713
Opened 2021-01-26 02:30 UTC by yHoonyK

## Check before PR

- [x] PR Title
- [x] Link issue or no issue to link
- [x] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [x] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

2021-01-26 02:51 UTC, Minddol requested changes

2021-01-26 02:51 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +        var payload = [String: AnyHashable?]()
69 line 에서 payload 가 덮어써져서 version 이 71 line 으로 가야 할 것 같아요.

2021-01-26 02:51 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
https://tde.sktelecom.com/wiki/display/ERECTUS/03.+InteractionControl
Message.SendCandidates 도 InteractionControl 대상입니다.

2021-01-26 03:21 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +        var payload = [String: AnyHashable?]()
수정했습니다.

2021-01-26 03:21 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
적용했습니다.

2021-01-26 03:22 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
폰콜이랑 똑같이 적용하긴 했는데, 
잘 적용 됐는지 한번만 봐주시고 resolve 해주시면 좋을 것 같아요.

2021-01-26 04:17 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
아... 이거 PhoneCallAgent 도 수정되어야 하네요,
Play 작업이 아직 안되었을 때 구현했던거라...
`DisplayAgent.handleControlScroll` 참고해서 payload 에 `interactionControl` 추가해서 분기처리 부탁드려요.
Android 는 이미 분기처리 되어 있네요~

2021-01-26 09:17 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
초기 작업은 해뒀는데, 잔여개발하고 다시 검토 요청 드리겠습니다.

2021-02-01 06:50 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
> +
interaction control 적용됐습니다.

2021-02-01 06:53 UTC, Minddol approved these changes

2021-02-01 06:57 UTC, jin-marino approved these changes

2021-02-01 07:42 UTC, childc approved these changes

2021-02-01 07:46 UTC, merged