Put the resources for signal processing into the frameworks
nugu-developers/nugu-ios pull request #752
Opened 2021-02-22 08:41 UTC by childc

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-02-22 09:04 UTC, Minddol requested changes

2021-02-22 09:04 UTC, Minddol commented on nugu-ios.xcodeproj/project.pbxproj
> -		7E3C570F2450049C00FF36DF /* Keyword.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7E3C570E2450049C00FF36DF /* Keyword.swift */; };
Reference 만 지워지고 파일은 남아 있는 것 같아요~

2021-02-22 09:04 UTC, Minddol commented on nugu-ios.xcodeproj/project.pbxproj
> +		F7AA6E4025E39C8E00C852D5 /* skt_epd_model.raw in Resources */ = {isa = PBXBuildFile; fileRef = F7AA6E3F25E39C8E00C852D5 /* skt_epd_model.raw */; };
KeenSense.podspec, JadeMarble.podspec 파일에 resources 설정해야 하지 않나요?

2021-02-22 13:56 UTC, childc commented on nugu-ios.xcodeproj/project.pbxproj
> +		F7AA6E4025E39C8E00C852D5 /* skt_epd_model.raw in Resources */ = {isa = PBXBuildFile; fileRef = F7AA6E3F25E39C8E00C852D5 /* skt_epd_model.raw */; };
아네.. cocoapods를 빼먹었네요

2021-02-23 03:02 UTC, Minddol approved these changes

2021-02-23 06:29 UTC, yHoonyK approved these changes

2021-02-23 06:30 UTC, jin-marino approved these changes

2021-02-23 06:57 UTC, merged