`ASRAgent` 1.6 (upgrade capability-agent)
nugu-developers/nugu-ios pull request #767
Opened 2021-03-03 04:14 UTC by Minddol

## Check before PR

- [x] PR Title
- [x] Link issue or no issue to link
- [x] README.md
- [x] Code-level documentation

## Version

- [ ] Update major
- [x] Update minor
- [ ] Update patch

## Need when updating version

- [x] NUGU Developers
- [ ] Github Wiki

## Summary

2021-03-03 05:58 UTC, childc approved these changes

2021-03-04 00:19 UTC, jin-marino commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
> +    public var capabilityAgentProperty: CapabilityAgentProperty = CapabilityAgentProperty(category: .automaticSpeechRecognition, version: "1.5")
title 은 1.6 이고 코드는 1.5이네요, 1.5 인거죠?

2021-03-04 00:20 UTC, jin-marino approved these changes

2021-03-05 06:59 UTC, yHoonyK requested changes

2021-03-05 06:59 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
> +    public var capabilityAgentProperty: CapabilityAgentProperty = CapabilityAgentProperty(category: .automaticSpeechRecognition, version: "1.5")
타이틀을 수정해야 하지 않을까 싶은데 확인 부탁드려요 ㅎ

2021-03-05 07:00 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
> +    public var capabilityAgentProperty: CapabilityAgentProperty = CapabilityAgentProperty(category: .automaticSpeechRecognition, version: "1.5")
헛;; 네네 1.5 입니다. 수정했습니다.

2021-03-05 07:01 UTC, yHoonyK approved these changes

2021-03-05 07:05 UTC, merged