Upgrade `AudioPlayerAgent` to 1.6
nugu-developers/nugu-ios pull request #774
Opened 2021-03-08 02:08 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-03-08 02:13 UTC, jin-marino commented
AudioPlayerAgent 1.6 업그레이드 되면서, AudioDisplayTemplate 에 showButton 인자가 추가되어 AudioPlayer2View 에도 뉴스 요약문 보기가 추가되었습니다.
Lyrics 관련 코드들이 공통 요소로 바뀌면서 AudioDisplayView 로 많이 옮겨졌습니다.
추가적으로 가사뷰의 사이즈 수정이 적용되었고, 페이지 컨트롤 이벤트 전송 시 버그를 수정하였습니다.

2021-03-08 02:52 UTC, Minddol approved these changes

2021-03-09 03:11 UTC, yHoonyK approved these changes

2021-03-09 03:19 UTC, childc requested changes

2021-03-09 03:19 UTC, childc commented on NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
> +        return !lyricsView.isHidden
lyricsView.isHidden == false 와 같은 표기법으로 수정 부탁드려요~

2021-03-09 03:19 UTC, childc commented on NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
> +              fullAudioPlayerContainerView.subviews.contains(fullLyricsView) == true else {
🤟🏻

2021-03-09 03:19 UTC, childc commented on NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
> +        }
Multi-thread가능성이 있다면 
```
let fullLyricsView = FullLyricsView(frame: CGRect(origin:~~~~~
// ~~~
self.fullLyricsView = fullLyricsView
```
와 같은 방식으로 하는것이 더 나을 것 같습니다.

multi-thread가능성확인 한번 부탁드려요~

2021-03-09 04:25 UTC, jin-marino commented on NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
> +        return !lyricsView.isHidden
수정하였습니다~

2021-03-09 04:26 UTC, jin-marino commented on NuguUIKit/Sources/AudioDisplayView/AudioDisplayView.swift
> +        }
수정 반영하였습니다, 확인 부탁드려요~

2021-03-09 11:16 UTC, childc approved these changes

2021-03-09 23:31 UTC, merged