Add `DeviceUniqueId` varible to `NuguServiceCookie`
nugu-developers/nugu-ios pull request #776
Opened 2021-03-10 06:02 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-03-10 06:17 UTC, Minddol approved these changes

2021-03-10 08:34 UTC, childc approved these changes

2021-03-11 07:23 UTC, yHoonyK approved these changes

2021-03-11 07:24 UTC, yHoonyK commented
진님 커밋로그가 꼬여있는것같은데 확인이 필요해보여요~

2021-03-11 07:24 UTC, yHoonyK requested changes

2021-03-11 07:24 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
>      public lazy var contextInfoProvider: ContextInfoProviderType = { [weak self] completion in
PR에 커밋 여러개가 꼬여있는것같은데 확인이 필요해보입니다.

2021-03-11 07:49 UTC, Minddol approved these changes

2021-03-11 07:49 UTC, Minddol commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
>      public lazy var contextInfoProvider: ContextInfoProviderType = { [weak self] completion in
이거 제가 develop/1.0.0 새로 만들면서 conflict resolve 제대로 못해서 누락됐었나봐요 ㅠㅠ
`let payload: [String: AnyHashable?]` 이게 맞아요;;

2021-03-11 07:55 UTC, yHoonyK commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
>      public lazy var contextInfoProvider: ContextInfoProviderType = { [weak self] completion in
아 코드에 문제는 아니고, 커밋이 51개가 들어가있던데 괜찮은건가요~?

2021-03-11 08:19 UTC, jin-marino commented on NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
>      public lazy var contextInfoProvider: ContextInfoProviderType = { [weak self] completion in
저도 왜 커밋이 저렇게 된건지 모르겠네요.. files changed 항목에 문제가 없어서 그냥 진행했는데 왜 이런걸까요? 혹시 아시는분?

2021-03-11 08:29 UTC, closed without merging