Add `setCustomCookie` to `NuguServiceWebView`
nugu-developers/nugu-ios pull request #797
Opened 2021-03-23 10:08 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-03-23 10:09 UTC, jin-marino commented
https://tde.sktelecom.com/pms/browse/ROUTINE-20
기존 NuguServiceCookie 로 쿠키 세팅하던 것을 deprecate 시키고,
setCustomCookie 메소드를 추가하였습니다.

2021-03-23 10:19 UTC, Minddol commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +
theme 는 customCookie 에 넣을 수 있는건가요?
deviceUniqueId 는 customCookie 로 넣을 수 없는건가요?

2021-03-23 10:40 UTC, jin-marino commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +
말씀하신대로 이상해보여 parameter 에 theme 도 추가하였습니다. 혹시 다른 의견이시면 말씀주세요~

2021-03-24 07:51 UTC, yHoonyK requested changes

2021-03-24 07:51 UTC, yHoonyK commented on NuguServiceKit/Sources/NuguServiceWebView.swift
> +    func setCustomCookie(customCookieDictionary: [String: Any]) {
```suggestion
    func setCookie(_ cookie: [String: Any]) {
```
정도로 하는게 좋지 않을까요?

2021-03-24 07:51 UTC, yHoonyK commented on NuguUIKit/Sources/Extension/Container+Merge.swift
> +public extension Dictionary {
NuguUIKit에 있는 extension을 위해서 import 시키는것보다는
NuguUtils로 옮기는게 좋지 않을까요~?
NuguCore에도 딥머지관련 중복코드가 있으니, NuguUtils로 통합시키면 좋을 것 같습니다.

2021-03-24 07:51 UTC, yHoonyK commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +        let cookie = NuguServiceCookie(
`NuguServiceCookie` 도 없애버리고,
`setCustomCookie(_ customCookie: [String: Any])`로 변경해서
그냥 `deviceUniqueId`도 딕셔너리로 받으면 가이드 하기가 어려울까요~?
디폴드값 넣어주고, 딕셔너리에 있는걸 딥머지 하는 형식으로 가는게 그냥 깔끔할 것 같긴한데,
고려해봐주세요.
(NuguServiceCookie는 가급적 삭제하고 디폴드값 정도만 관리하는게 좋아보이긴하네요.)

2021-03-24 07:52 UTC, Minddol commented on NuguServiceKit/Sources/NuguServiceWebView.swift
> +    func setCustomCookie(customCookieDictionary: [String: Any]) {
저도 이게 좋을 것 같아요~

2021-03-24 07:53 UTC, yHoonyK commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +    @available(*, deprecated, message: "Use `setCustomCookie` instead")
1.0.0까지는 API deprecated는 그냥 삭제하는걸로 어디선가 결정했던 것 같은데, 
1.0.0 이후부터 deprecated 처리하시죠. 지금 다른 곳에 있는건 제가 제거할게요~

2021-03-24 08:35 UTC, jin-marino commented on NuguServiceKit/Sources/NuguServiceWebView.swift
> +    func setCustomCookie(customCookieDictionary: [String: Any]) {
반영하였습니다~

2021-03-24 08:36 UTC, jin-marino commented on NuguUIKit/Sources/Extension/Container+Merge.swift
> +public extension Dictionary {
반영하였습니다~

2021-03-24 08:37 UTC, jin-marino commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +        let cookie = NuguServiceCookie(
NuguClient 에서는 overwrite 가능한 addCookie, NUguServiceWebView 에는 default 없는 setCookie 로 수정하였습니다.

2021-03-24 08:37 UTC, jin-marino commented on NuguClientKit/Sources/Extensions/NuguServiceWebView+Convenience.swift
> +    @available(*, deprecated, message: "Use `setCustomCookie` instead")
이걸로 0.30.1 먼저 나가면 이후에 삭제하겠습니다~

2021-03-24 09:23 UTC, jin-marino commented
본 PR 의 타겟을 1.0.0 으로 변경함에따라 `NuguServiceCookie` 와 관계된 함수들을 삭제하였습니다~

2021-03-24 19:43 UTC, childc approved these changes

2021-03-30 01:31 UTC, closed without merging

2021-03-30 10:20 UTC, Minddol commented
@jin-marino 님, 1.1.0 으로 다시 올려주세요~