Add startMicWorkItemQueue for sync execute of workItem
nugu-developers/nugu-ios pull request #877
Opened 2021-07-07 09:10 UTC by jin-marino

## Check before PR

- [ ] PR Title
- [ ] Link issue or no issue to link
- [ ] README.md
- [ ] Code-level documentation

## Version

- [ ] Update major
- [ ] Update minor
- [ ] Update patch

## Need when updating version

- [ ] NUGU Developers
- [ ] Github Wiki

## Summary

2021-07-09 05:38 UTC, yHoonyK approved these changes

2021-07-12 18:38 UTC, childc commented
DispatchQueue를 명시적으로 생성하는 것 보다는, @Atomic을 사용하고 atomic mutate를 통해 cancel과 할당이 겹치지 않게 해결하는 것이 더 좋을 것 같습니다

2021-07-12 18:39 UTC, childc requested changes
`startMicWorkItem`을 @Atomic으로 선언하고 mutate를 사용하는 것이 더 좋을 것 같습니다.

2021-07-13 00:49 UTC, childc approved these changes

2021-07-13 01:59 UTC, merged